// Package buildimage assembles Docker build contexts for prebaked agent images.
package buildimage

import (
	"fmt"
	"strings"
)

// GenerateDockerfile returns Dockerfile content for a prebaked agent image.
// The generated image copies the pre-staged workspace directory and touches
// the ready sentinel so the entrypoint skips the wait.
func GenerateDockerfile(baseImage string) []byte {
	// Reject newlines to prevent Dockerfile directive injection.
	if strings.ContainsAny(baseImage, "\n\r") {
		baseImage = strings.NewReplacer("\n", "", "\r", "").Replace(baseImage)
	}
	const tmpl = `# Generated by: gc build-image
ARG BASE=%s
FROM ${BASE}
USER root
COPY workspace/ /workspace/
# chown to gcagent (default). When LINUX_USERNAME is set at runtime, the pod
# entrypoint re-chowns the workspace to the dynamic user.
RUN chown -R gcagent:gcagent /workspace && touch /workspace/.gc-workspace-ready
USER gcagent
`
	return []byte(fmt.Sprintf(tmpl, baseImage))
}
